# -*- coding: utf-8 -*-
"""Questão_4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a4F7GggHfYd1eIWJsONqc2RcZCsJOF52

Questão 04:
Faça um programa que leia uma matriz 3x3 de inteiros e retorne a linha de maior soma. Imprima na tela a matriz, a linha de maior soma e a soma.
"""

matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print("Matriz:")
for linha in matriz:
    print(linha)
soma_linha = [sum(linha) for linha in matriz]
print("linha de maior soma:", soma_linha.index(max(soma_linha)))
print("soma:", max(soma_linha))