# -*- coding: utf-8 -*-
"""questão_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbQazvPWMqKRy51t7_1ciuantCeikkG_

Questões 01:
Faça um programa que leia uma matriz 3x3 e multiplique os elementos da diagonal principal da matriz por um número k. Imprima a matriz na tela antes e depois da multiplicação
"""

matriz_3x3 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(matriz_3x3)

mult_diagonal = matriz_3x3[0][0] * matriz_3x3[1][1] * matriz_3x3[2][2] * 2
print(mult_diagonal)