# -*- coding: utf-8 -*-
"""Questão_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Aw6DO7SgzbjQ1um3fbqAIte-0XxPq-Ur

Questão 03:
Glossário: Um dicionário Python pode ser usado para modelar um dicionário real. No entanto, para evitar confusão, vamos chamá-lo de glossário. Pense em cinco palavras de programação que você aprendeu nos capítulos anteriores. Use essas palavras como chaves em seu glossário armazene seus significados como valores. Imprima cada palavra e seu significado como saída bem formatada. Você pode imprimir a palavra seguida de dois pontos e depois o seu significado, ou imprimir a palavra em uma linha e, em seguida, imprimir seu significado recuado em uma segunda linha. Use o caractere de nova linha (\n) para inserir uma linha em branco entre cada par palavra-significado em sua saída.
"""

glossario = {

    'funcao' : 'instruções',
    'tupla': 'imutável',
    'dicionário': 'mapeamento',
    'lista': 'coleção',
    'Conjunto': 'contêiner'
}

for palavra, significado in glossario.items():
    print(f"\n{palavra.title()}: {significado.title()}")